server:
  port: 9001

spring:
  kafka:
    #bootstrap-servers: http://${HOST_IP}:9092
    bootstrap-servers: http://host.docker.internal:9092
  sleuth:
    messaging:
      kafka:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    kafka:
      topic: blunt-onboard
    sender:
      type: kafka
  data:
    mongodb:
      uri: mongodb+srv://blunt:blunt@clusterblunt-ozeey.gcp.mongodb.net/onboard?retryWrites=true&w=majority
  boot:
    admin:
      client:
        # url: http://${HOST_IP}:9000
        url: http://host.docker.internal:9000
        instance:
          health-url: http://host.docker.internal:9001/actuator/health
          management-url: http://host.docker.internal:9001/actuator
          service-url: http://host.docker.internal:9001
management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  client:
    config:
      follow-service:
        connectTimeout: 15000
        readTimeout: 15000
      sms-service:
        connectTimeout: 15000
        readTimeout: 15000

logging:
  file:
    path: C:/Users/kpaulpa/Documents/workArea/TechnicalWork/logs/blunt-onboard-service
