server:
  port: 9002

spring:
  kafka:
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="52753t8t" password="74rKya8PhAYtNPG-HXePy2QK2-UbuCUR";
    bootstrap-servers: velomobile-01.srvs.cloudkafka.com:9094, velomobile-02.srvs.cloudkafka.com:9094, velomobile-03.srvs.cloudkafka.com:9094
    consumer:
      group-id: 52753t8t-follow-consumer
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.blunt.follow.dto
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  sleuth:
    messaging:
      kafka:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    kafka:
      topic: 52753t8t-zipkin-blunt-follow
    sender:
      type: web
  data:
    mongodb:
      uri: mongodb+srv://blunt:blunt@clusterblunt-ozeey.gcp.mongodb.net/follow?retryWrites=true&w=majority
  boot:
    admin:
      client:
        # url: http://${HOST_IP}:9000
        url: http://host.docker.internal:9000
        instance:
          health-url: http://host.docker.internal:9002/actuator/health
          management-url: http://host.docker.internal:9002/actuator
          service-url: http://host.docker.internal:9002
management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  client:
    config:
      publish-service:
        connectTimeout: 15000
        readTimeout: 15000

logging:
  file:
    path: C:/Users/kpaulpa/Documents/workArea/TechnicalWork/logs/blunt-follow-service
