server:
  port: 9004

spring:
  kafka:
    #bootstrap-servers: http://${HOST_IP}:9092
    bootstrap-servers: http://host.docker.internal:9092
  sleuth:
    messaging:
      kafka:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    kafka:
      topic: blunt-publish
    sender:
      type: kafka
  data:
    mongodb:
      uri: mongodb+srv://blunt:blunt@clusterblunt-ozeey.gcp.mongodb.net/publish?retryWrites=true&w=majority
  boot:
    admin:
      client:
        # url: http://${HOST_IP}:9000
        url: http://host.docker.internal:9000
        instance:
          health-url: http://host.docker.internal:9002/actuator/health
          management-url: http://host.docker.internal:9002/actuator
          service-url: http://host.docker.internal:9002
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    path: C:/Users/kpaulpa/Documents/workArea/TechnicalWork/logs/blunt-publish-service
