server:
  port: 8765

zuul:
  routes:
    onboard-service:
      path: /api/v1/onboard/**
      stripPrefix: false
    follow-service:
      path: /api/v1/follow/**
      stripPrefix: false
    sms-service:
      path: /api/v1/sms/**
      stripPrefix: false
    publish-service:
      path: /api/v1/publish/**
      stripPrefix: false
    email-service:
      path: /api/v1/email/**
      stripPrefix: false
    metrics-service:
      path: /api/v1/metrics/**
      stripPrefix: false
    comments-service:
      path: /api/v1/comments/**
      stripPrefix: false
    authentication-service:
      path: /api/v1/authenticate/**
      stripPrefix: false
  host:
    connect-timeout-millis: 37000
    socket-timeout-millis: 37000

ribbon:
  ReadTimeout: 37000
  SocketTimeout: 37000
  ConnectTimeout: 37000


spring:
  kafka:
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="52753t8t" password="74rKya8PhAYtNPG-HXePy2QK2-UbuCUR";
      bootstrap-servers: velomobile-01.srvs.cloudkafka.com:9094, velomobile-02.srvs.cloudkafka.com:9094, velomobile-03.srvs.cloudkafka.com:9094
      consumer:
        group-id: 52753t8t-gateway-consumer
        auto-offset-reset: latest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring:
            json:
              trusted:
                packages: com.blunt.gateway.dto
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  sleuth:
    messaging:
      kafka:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    kafka:
      topic: 52753t8t-zipkin-blunt-gateway
    sender:
      type: kafka
  boot:
    admin:
      client:
        # url: http://${HOST_IP}:9000
        url: http://host.docker.internal:9000
        instance:
          health-url: http://host.docker.internal:8765/actuator/health
          management-url: http://host.docker.internal:8765/actuator
          service-url: http://host.docker.internal:9006
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    path: C:/Users/kpaulpa/Documents/workArea/TechnicalWork/logs/blunt-gateway-service

