server:
  port: 9003

spring:
  kafka:
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="lrodt96d" password="WJMm23WrfaHhiropNEIiUhg9-jeurivt";
    bootstrap-servers: moped-01.srvs.cloudkafka.com:9094, moped-02.srvs.cloudkafka.com:9094, moped-03.srvs.cloudkafka.com:9094
    consumer:
      group-id: lrodt96d-sms-consumer
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.blunt.sms.dto
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  sleuth:
    messaging:
      kafka:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    kafka:
      topic: lrodt96d-zipkin-blunt-sms
    sender:
      type: web
  data:
    mongodb:
      uri: mongodb+srv://blunt:blunt@clusterblunt-ozeey.gcp.mongodb.net/sms?retryWrites=true&w=majority
  boot:
    admin:
      client:
        # url: http://${HOST_IP}:9000
        url: http://host.docker.internal:9000
        instance:
          health-url: http://host.docker.internal:9003/actuator/health
          management-url: http://host.docker.internal:9003/actuator
          service-url: http://host.docker.internal:9003
management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  httpclient:
    connection-timeout: 6000

logging:
  file:
    path: C:/Users/kpaulpa/Documents/workArea/TechnicalWork/logs/blunt-sms-service

twilio:
  sid: AC7212fa2d8057ae09117bc2407afb6611
  token: 1d41ee14db1cb9dbd9fdbfb55b9c3419
  messageCenter: whatsapp:+14155238886

text-local:
  api-key: Vm73vOXE764-7F2LLNRknABp4oCLmiDB51EqUMgQNr
  sender: TXTLCL
  url: https://api.textlocal.in/send
